# Generated by Django 6.0.1 on 2026-08-17 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chaptercategory',
            options={'verbose_name_plural': 'Chapter Categories'},
        ),
        migrations.AlterModelOptions(
            name='examcategory',
            options={'verbose_name_plural': 'Exam Categories'},
        ),
        migrations.AlterModelOptions(
            name='subjectcategory',
            options={'verbose_name_plural': 'Subject Categories'},
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='demo_expiry_date',
            field=models.DateTimeField(blank=True, help_text='डेमो समाप्त होने की तारीख (एडमिन कंट्रोल)', null=True),
        ),
    ]
