# Generated by Django 6.0.1 on 2026-08-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_chaptercategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chaptercategory',
            options={'ordering': ['sequence'], 'verbose_name_plural': 'Chapter Categories'},
        ),
        migrations.AddField(
            model_name='chaptercategory',
            name='sequence',
            field=models.IntegerField(default=0, help_text='चैप्टर का सही क्रम डालें (जैसे 1, 2, 3)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=255),
        ),
    ]
