# Generated by Django 6.0.7 on 2026-07-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_testattempt_studentanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='mocktest',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, help_text='टेस्ट शुरू होने का समय (वैकल्पिक)', null=True),
        ),
    ]
