# Generated by Django 6.0.7 on 2026-07-27 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_questioncategory_questionsubcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questioncategory',
            name='name',
            field=models.CharField(help_text='e.g., Class 9, Class 10', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='questionsubcategory',
            name='name',
            field=models.CharField(help_text='e.g., Physics, Math', max_length=100),
        ),
        migrations.CreateModel(
            name='QuestionChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Motion, Force and Laws of Motion', max_length=150)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='portal.questionsubcategory')),
            ],
            options={
                'unique_together': {('subcategory', 'name')},
            },
        ),
        migrations.AddField(
            model_name='globalquestionbank',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.questionchapter'),
        ),
    ]
