# Generated by Django 6.0.7 on 2026-07-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_alter_questioncategory_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
