# Generated by Django 6.0.7 on 2026-07-31 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_customuser_last_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='subscription_expiry_date',
            field=models.DateTimeField(blank=True, help_text='पेमेंट वाला सब्सक्रिप्शन कब खत्म होगा', null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='trial_expiry_date',
            field=models.DateTimeField(blank=True, help_text='72 घंटे का फ्री ट्रायल कब खत्म होगा', null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='छात्र का वॉलेट बैलेंस (इनाम या रिचार्ज)', max_digits=10),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='admin_commission',
            field=models.DecimalField(decimal_places=2, default=49.0, help_text='इस फीस में एडमिन का हिस्सा', max_digits=10),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='subscription_fee',
            field=models.DecimalField(decimal_places=2, default=99.0, help_text='छात्र से ली जाने वाली फीस', max_digits=10),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='subscription_validity_days',
            field=models.IntegerField(default=30, help_text='यह पैकेज कितने दिन चलेगा?'),
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('SUBSCRIPTION', 'Test Subscription'), ('WALLET_RECHARGE', 'Wallet Recharge')], default='SUBSCRIPTION', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('razorpay_order_id', models.CharField(max_length=100, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('CREDIT', 'Credit (पैसे आए)'), ('DEBIT', 'Debit (पैसे कटे)')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(help_text='उदा: इनाम मिला, सब्सक्रिप्शन खरीदा, या बैंक में निकाले', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
