# Generated by Django 6.0.1 on 2026-08-02 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_studentprofile_subscription_expiry_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('UPI', 'UPI ID'), ('BANK', 'Bank Account')], default='UPI', max_length=50)),
                ('payment_details', models.CharField(help_text='अपना UPI ID या बैंक डिटेल्स यहाँ डालें', max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending (लंबित)'), ('APPROVED', 'Approved (सफल)'), ('REJECTED', 'Rejected (रद्द)')], default='PENDING', max_length=20)),
                ('admin_note', models.TextField(blank=True, help_text='अगर रिक्वेस्ट रिजेक्ट की है, तो उसका कारण', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
