# Generated by Django 6.0.1 on 2026-08-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_withdrawalrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to='question_images/'),
        ),
    ]
