"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-brst)0x%f9s3_vo+3@=_@rpt9631$)0bk8ov&&yr4_$v4-)di*'

# SECURITY WARNING: don't run with debug turned on in production!
# 🚀 Render और Local दोनों पर काम करने के लिए स्मार्ट DEBUG
DEBUG = 'RENDER' not in os.environ

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'portal',  # यहाँ हमने अपना नया ऐप जोड़ दिया
]


AUTH_USER_MODEL = 'portal.CustomUser'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # 🚀 Static files को Render पर चलाने के लिए
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# यह कोड लोकल कंप्यूटर पर SQLite चलाएगा, लेकिन Render (लाइव) पर ऑटोमैटिक PostgreSQL चलाएगा
# सिर्फ 5 मिनट के लिए इस कोड को ऐसे बदल दें:
# काम हो जाने के बाद इसे वापस ऐसा कर दें:
DATABASES = {
    'default': dj_database_url.config(
        default='sqlite:///' + str(BASE_DIR / 'db.sqlite3'),
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

# 🚀 Indian Time Zone
TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True
USE_L10N = True
USE_TZ = True # यह True ही रहने दें


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # 🚀 NEW

# यह लाइन Django को बताएगी कि आपकी इमेजेज कहाँ रखी हैं
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# 🚀 Render पर CSS/JS को सही से लोड करने के लिए WhiteNoise स्टोरेज
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# Custom Login URL
LOGIN_URL = 'login'


# Razorpay Settings
RAZORPAY_KEY_ID = 'rzp_test_T3sERZ1EG27ZEy'
RAZORPAY_KEY_SECRET = 'cTbUNPOgbI6RZEuTI2NzDYXE'


# Media Files Settings
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


import os

# ==========================================
# 📧 EMAIL SMTP SETTINGS
# ==========================================
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 465
EMAIL_USE_SSL = True

# 🚀 यहाँ 'your_actual_email@gmail.com' की जगह अपना असली ईमेल
# और '16_digit_password' की जगह अपना असली ऐप पासवर्ड डाल दें।
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'your_actual_email@gmail.com')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '16_digit_password')

DEFAULT_FROM_EMAIL = f'Mock Test Portal <{EMAIL_HOST_USER}>'